export type ActivityChoice =
  | "Notifications"
  | "Client Work"
  | "Meeting"
  | "Personal Work"
  | "Gaming"
  | "Exercising"
  | "AFK"
  | "Nothing"
  | "Reading"
  | "Streaming"
  | "Socialising"
  | "Game Dev"
  | "Signing Off"
  | "Sleeping";
